# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openkanban < Formula
  desc "TUI kanban board for orchestrating AI coding agents"
  homepage "https://github.com/TechDufus/openkanban"
  version "0.0.2"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TechDufus/openkanban/releases/download/v0.0.2/openkanban_0.0.2_darwin_amd64.tar.gz"
      sha256 "8adb0f21fb651e05eb429ae52346d2b3bc0a6a49a98b0fa5d91495cb8d688f2c"

      def install
        bin.install "openkanban"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TechDufus/openkanban/releases/download/v0.0.2/openkanban_0.0.2_darwin_arm64.tar.gz"
      sha256 "36e21fcae8f02818eba1bcfb412af441318139c53d889ba84b8b0941fbb156c4"

      def install
        bin.install "openkanban"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TechDufus/openkanban/releases/download/v0.0.2/openkanban_0.0.2_linux_amd64.tar.gz"
      sha256 "4d6c1eade0cadef9f1872390723512667b8bfd83d9c7f16835a62b524d9a7354"
      def install
        bin.install "openkanban"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TechDufus/openkanban/releases/download/v0.0.2/openkanban_0.0.2_linux_arm64.tar.gz"
      sha256 "c889b34d4fd6595f245e2ccfef1ec669cf4f70f91746ea516f08eba7bfb0cb44"
      def install
        bin.install "openkanban"
      end
    end
  end

  test do
    system "#{bin}/openkanban", "version"
  end
end
