# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openkanban < Formula
  desc "TUI kanban board for orchestrating AI coding agents"
  homepage "https://github.com/TechDufus/openkanban"
  version "0.0.1"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TechDufus/openkanban/releases/download/v0.0.1/openkanban_0.0.1_darwin_amd64.tar.gz"
      sha256 "7c7c403944f248ae417c0950d548dc13f2acaf76c615731e0765baebd82c4a15"

      def install
        bin.install "openkanban"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TechDufus/openkanban/releases/download/v0.0.1/openkanban_0.0.1_darwin_arm64.tar.gz"
      sha256 "4dc9579c695ad2fce452df5e5c3d7b08279d1e581c818a533cc975cafbc05cdd"

      def install
        bin.install "openkanban"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TechDufus/openkanban/releases/download/v0.0.1/openkanban_0.0.1_linux_amd64.tar.gz"
      sha256 "0d32131fa3ca15ba0194a45676e6010e2ead7f57a92704bf629e4c418a803b8b"
      def install
        bin.install "openkanban"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TechDufus/openkanban/releases/download/v0.0.1/openkanban_0.0.1_linux_arm64.tar.gz"
      sha256 "4d1ec7d7d1f9031be7f9d59bb31ac2cac657fae520100bf71b95fbe91b54b773"
      def install
        bin.install "openkanban"
      end
    end
  end

  test do
    system "#{bin}/openkanban", "version"
  end
end
