# This file was generated by GoReleaser. DO NOT EDIT.
cask "openkanban" do
  name "openkanban"
  desc "TUI kanban board for orchestrating AI coding agents"
  homepage "https://github.com/TechDufus/openkanban"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openkanban"

  on_macos do
    on_intel do
      url "https://github.com/TechDufus/openkanban/releases/download/v#{version}/openkanban_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/TechDufus/openkanban"
      sha256 "06e97bccabf7f767d6c2165b766df6b3784bc40657a7a10a42c2b4149f55f092"
    end
    on_arm do
      url "https://github.com/TechDufus/openkanban/releases/download/v#{version}/openkanban_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/TechDufus/openkanban"
      sha256 "e59ad98d8ee4a388f8fc12ccfe739c68b1b17b967981e223847ab5042ad33fac"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/TechDufus/openkanban/releases/download/v#{version}/openkanban_#{version}_linux_amd64.tar.gz",
        verified: "github.com/TechDufus/openkanban"
      sha256 "2187e0afa41465242ea8228de2f5e3eb7c17f28605aeffa4d279c1bfdd681133"
    end
    on_arm do
      url "https://github.com/TechDufus/openkanban/releases/download/v#{version}/openkanban_#{version}_linux_arm64.tar.gz",
        verified: "github.com/TechDufus/openkanban"
      sha256 "f51c5751525c7c2683690861d02eb2cfaf494fb580799c12001cdafe11d5c33d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openkanban"]
    end
  end

  # No zap stanza required
end
