# This file was generated by GoReleaser. DO NOT EDIT.
cask "openkanban" do
  name "openkanban"
  desc "TUI kanban board for orchestrating AI coding agents"
  homepage "https://github.com/TechDufus/openkanban"
  version "0.0.23"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openkanban"

  on_macos do
    on_intel do
      url "https://github.com/TechDufus/openkanban/releases/download/v#{version}/openkanban_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/TechDufus/openkanban"
      sha256 "16ddcadf64fb824709a3b2a8d5e90fa788bee9ea30bd1ca45e131071456c31ed"
    end
    on_arm do
      url "https://github.com/TechDufus/openkanban/releases/download/v#{version}/openkanban_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/TechDufus/openkanban"
      sha256 "b470cc9c85e35b1840c95d9a1bfbc9830fe47e8ee1c713dc60a036d1b47d3212"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/TechDufus/openkanban/releases/download/v#{version}/openkanban_#{version}_linux_amd64.tar.gz",
        verified: "github.com/TechDufus/openkanban"
      sha256 "16fd115a3be4edd6388cf00d007c0efb64cf89e6f557e931e7cf4693feaa26c4"
    end
    on_arm do
      url "https://github.com/TechDufus/openkanban/releases/download/v#{version}/openkanban_#{version}_linux_arm64.tar.gz",
        verified: "github.com/TechDufus/openkanban"
      sha256 "84abc1ad241040af486de5edda5b687fa85674f7dfab33fd20f9b8c148b95f89"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openkanban"]
    end
  end

  # No zap stanza required
end
