# This file was generated by GoReleaser. DO NOT EDIT.
cask "openkanban" do
  name "openkanban"
  desc "TUI kanban board for orchestrating AI coding agents"
  homepage "https://github.com/TechDufus/openkanban"
  version "0.0.33"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openkanban"

  on_macos do
    on_intel do
      url "https://github.com/TechDufus/openkanban/releases/download/v#{version}/openkanban_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/TechDufus/openkanban"
      sha256 "e6448c43ed780fa1b7c37c9fad23909608e8db81adf4520de0b24b2969717aec"
    end
    on_arm do
      url "https://github.com/TechDufus/openkanban/releases/download/v#{version}/openkanban_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/TechDufus/openkanban"
      sha256 "2dc065a778c169a1d371899f7fc38e10bd0cf0ea36f8ae057787ca85593fa63a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/TechDufus/openkanban/releases/download/v#{version}/openkanban_#{version}_linux_amd64.tar.gz",
        verified: "github.com/TechDufus/openkanban"
      sha256 "6460967866e4cb0f84a6f126b0a1c02be90550131fb81536df159b060ae9b0d8"
    end
    on_arm do
      url "https://github.com/TechDufus/openkanban/releases/download/v#{version}/openkanban_#{version}_linux_arm64.tar.gz",
        verified: "github.com/TechDufus/openkanban"
      sha256 "97e85caaaec615e1f68646abb68b9fbef08dc6c8364906afe91319ca280e0928"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openkanban"]
    end
  end

  # No zap stanza required
end
